using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ExcelFlow.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public class MapperGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax c && c.AttributeLists.Count > 0,
                transform: static (ctx, _) =>
                {
                    var classDecl = (ClassDeclarationSyntax)ctx.Node;
                    bool hasAttr = classDecl.AttributeLists
                        .SelectMany(al => al.Attributes)
                        .Any(a => a.Name.ToString().Contains("ExcelFlowSerializable"));

                    return hasAttr ? ctx.SemanticModel.GetDeclaredSymbol(classDecl) as ITypeSymbol : null;
                })
            .Where(static m => m is not null);

        context.RegisterSourceOutput(classDeclarations, static (spc, source) => Execute(spc, source!));
    }

    private static void Execute(SourceProductionContext context, ITypeSymbol classSymbol)
    {
        try
        {
            string className = classSymbol.Name;
            string namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using ExcelFlow;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {className} : IExcelFlowSerializable<{className}>");
            sb.AppendLine("    {");

            sb.AppendLine($"        public static global::System.Collections.Generic.IEnumerable<global::ExcelFlow.ExcelColumnDefinition<{className}>> GetDefinitions()");
            sb.AppendLine("        {");

            var properties = classSymbol.GetMembers().OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public);

            foreach (var prop in properties)
            {
                var columnAttr = prop.GetAttributes().FirstOrDefault(ad =>
                    ad.AttributeClass?.Name.Contains("ExcelColumn") == true);

                string columnName = columnAttr != null && columnAttr.ConstructorArguments.Length > 0
                    ? columnAttr.ConstructorArguments[0].Value?.ToString() ?? prop.Name
                    : prop.Name;

                string propType = prop.Type.ToDisplayString();
                string propName = prop.Name;

                string typeofType = prop.Type.IsReferenceType
                    ? prop.Type.WithNullableAnnotation(NullableAnnotation.NotAnnotated).ToDisplayString()
                    : propType;

                string setterStr = prop.SetMethod is not null ? $"(item, val) => item.{propName} = ({propType})val!" : "null";
                string getterStr = prop.GetMethod is not null ? $"(item) => item.{propName}" : "null";

                sb.AppendLine($"            yield return new global::ExcelFlow.ExcelColumnDefinition<{className}>(");
                sb.AppendLine($"                \"{columnName}\",");
                sb.AppendLine($"                typeof({typeofType}),");
                sb.AppendLine($"                {setterStr},");
                sb.AppendLine($"                {getterStr}");
                sb.AppendLine($"            );");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
        catch (Exception ex)
        {
            throw new Exception($"On mapper generation error: {ex}");
        }
    }
}